In [2]:
import numpy as np

1. Create an array of 10 zeros
2. Create an array of 10 ones


In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3. Create an array of 10 fives

In [10]:
array = np.ones(10) * 5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Create an array of integers from 10-50

In [16]:
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [20]:
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
my_matrix = [[0,1,2], [3,4,5], [6,7,8]]
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Use numpy to generate a random number between 0 and 1

In [28]:
np.random.rand(1)

array([0.91842324])

Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
np.random.rand(5,5)

array([[0.39106022, 0.03098645, 0.71097608, 0.81431329, 0.91783932],
       [0.98284696, 0.44498169, 0.19656688, 0.53333911, 0.84048138],
       [0.48708292, 0.24997953, 0.17586033, 0.97046871, 0.19876862],
       [0.70596147, 0.09612854, 0.41934577, 0.38969854, 0.97243249],
       [0.40595835, 0.86467931, 0.03935019, 0.21125834, 0.96558011]])

In [44]:
arr = np.arange(1,51)
arr.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

Create an array of 20 linearly spaced points between 0 and 1

In [50]:
arr = np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [52]:
arr = np.arange(1,26)
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr = np.arange(16,26)
arr.reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
arr = np.arange(21,26)
print(arr)

[21 22 23 24 25]


In [88]:
arr = np.arange(1,26)
num = arr.reshape(5,5)
arr_3d = num
arr_3d[3,4]

20

In [109]:
arr_3d[:3,1]

array([ 2,  7, 12])

In [114]:
arr = np.arange(15,116,25)
print(arr)


[ 15  40  65  90 115]


In [117]:
arr = np.arange(1,26)
num = arr.reshape(5,5)
arr_3d = num
arr_3d[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])